<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->menuItem = $request->getRequestUri();

$string = substr($this->menuItem, 1);
$pos    = strpos($string, '/');
$lpos   = strpos($string, '/');
if ($pos !== false && $pos === $lpos) {
  $data = explode('/', $string);
  if (count($data) > 2) {
    $this->menuItem = '/' . $data[0] . '/' . $data[1];
    $item = '/' . $data[0];
  } else {
    $item = '/' . substr($string, 0, $lpos);
  }
} else {
  $item = '/' . $string;
}

?>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#frapi-navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="frapi-navbar">
      <ul class="nav navbar-nav">
        <li><a <?php echo $item == '/' ? ' class="active"' : '' ?> href="/"><?php echo $this->tr->_('DASHBOARD'); ?></a></li>
        <li><a <?php echo $item == '/action' ? ' class="active"' : '' ?> href="/action"><?php echo $this->tr->_('ACTIONS'); ?></a></li>
        <li><a <?php echo $item == '/mimetypes' ? ' class="active"' : '' ?> href="/mimetypes"><?php echo $this->tr->_('MIMETYPES'); ?></a></li>
        <li><a <?php echo $item == '/errors' ? ' class="active"' : '' ?> href="/errors"><?php echo $this->tr->_('ERRORS'); ?></a></li>
        <li><a <?php echo $item == '/partners' ? ' class="active"' : '' ?> href="/partners"><?php echo $this->tr->_('PARTNERS'); ?></a></li>
        <li><a <?php echo $item == '/configuration' ? ' class="active"' : '' ?> href="/configuration"><?php echo $this->tr->_('CONFIGURATION'); ?></a></li>
        <li><a <?php echo $item == '/tester' ? ' class="active"' : '' ?> href="/tester"><?php echo $this->tr->_('TESTER'); ?></a></li>
      </ul>
    </div>
    </div>
  </nav>
