
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="FRAPI <?php echo $this->tr->_('ADMIN_INTERFACE'); ?>."/>

<meta name="author" content="echolibre"/>
<link rel="shortcut icon" href="/gifs/favicon.ico" />
<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" media="all"/>
<link rel="stylesheet" type="text/css" href="/css/select2.min.css" media="all"/>
<!-- <link rel="stylesheet" type="text/css" href="/css/template.css" media="all"/> -->
<!-- <link rel="stylesheet" type="text/css" href="/css/frapi-specific.css" media="all"/> -->
<script src="/scripts/jquery-1.9.0.min.js" type="text/javascript"></script>
<script src="/scripts/bootstrap.min.js" type="text/javascript"></script>
<script src="/scripts/select2.min.js" type="text/javascript"></script>
<script src="/scripts/jquery.metadata.js" type="text/javascript"></script>
<script src="/scripts/jquery.uitablefilter.js" type="text/javascript"></script>
<script src="/scripts/jquery.tablesorter.min.js" type="text/javascript"></script>
<!-- compliance patch for microsoft browsers -->
<!--[if lt IE 8]><script src="/scripts/IE8.js" type="text/javascript"></script><![endif]-->
<link id="bespin_base" href="/bespin" />
<title>FRAPI <?php echo $this->tr->_('ADMIN_INTERFACE'); ?></title>
<script>
$(window).load(function(){
	$("table").addClass('table table-striped table-hover table-bordered');
	$("input[type='submit']").addClass('btn btn-primary btn-xl');
	$("form input[type='text'], button, select, input[type='password']").addClass('form-control').wrap("<div class='form-group'></div>");
	$("select").select2();
})
</script>
